-- MÓDULO: GASTOS DE CAMPO (VIÁTICOS) - NUEVOS CAMPOS

ALTER TABLE field_expenses
ADD COLUMN IF NOT EXISTS payment_method VARCHAR(50) DEFAULT 'transfer',
ADD COLUMN IF NOT EXISTS folio_fiscal VARCHAR(100),
ADD COLUMN IF NOT EXISTS area_destination VARCHAR(255);
